/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lesson_ndk_jni_HiJni */

#ifndef _Included_lesson_ndk_jni_HiJni
#define _Included_lesson_ndk_jni_HiJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lesson_ndk_jni_HiJni
 * Method:    getFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lesson_ndkjni_HiJni_getFromJni
  (JNIEnv *, jobject);

/*
 * Class:     lesson_ndk_jni_HiJni
 * Method:    setIntoJni
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lesson_ndkjni_HiJni_setIntoJni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
